### ISSUE TITLE
ModeleRenduPecheCommente.Rnw  : ajouter library(afd39)

### ISSUE THREAD

**Issue by adrienlavigne** [jbfagotfede39/aquatools#44]
Bug pour export des résultats car imposible de se connecter à poissons.resultats.BDD() une fois que le nombre de connections à la suite est atteint

<<library>>=
library(afd39)######à ajouter
library(aquatools)
library(fs)
library(ggplot2)
library(lubridate)
library(readxl)
library(reshape2)
library(RSQLite)
library(scales)
library(tidyverse)
library(xtable)
@

**Comment by jbfagotfede39** [comment]
Ok ce n'était pas clair au premier abord, mais en relisant le titre c'est tout bon.
Il faut ajouter la dépendance également dans ```ModeleRenduPeche.Rnw```
